config/routes.rb
Rails.application.routes.draw do

  
  resources :videos

  resources :soundcloud

  get 'content/reviews'
  
  get 'content/left_arrow'

  get 'content/right_arrow'

  get 'content/featured_works'

  get 'content/contact_us'

  post 'content/send_email'

  devise_for :admins, controllers: {
        sessions: 'admins/sessions'
      }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: "home#index"
end

app/models/video.rb
class Video < ApplicationRecord
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  def index
    if !admin_signed_in?
      redirect_to root_path
    end
    @lukes_compositions = Video.where(section: "lukes_compositions")
    @weird_phishes = Video.where(section: "weird_phishes")
    @wikr = Video.where(section: "wikr")
    @scoring_samples = Video.where(section: "scoring_samples")
    @featured_works = Video.where(section: "featured_works")
    @video = Video.new
    @soundcloud_playlists = Soundcloud.all
  end

  def new
    if !admin_signed_in?
      redirect_to root_path
    end
    @video = Video.new
    p params
    @section = params[:video][:section]
    p @section
  end

  def create
    if !admin_signed_in?
      redirect_to root_path
    end
    @video = Video.create(video_params)
    if @video.save
      redirect_to videos_path
    end
  end

  def edit
    if !admin_signed_in?
      redirect_to root_path
    end
    @video = Video.find(params[:id])
  end

  def update
    if !admin_signed_in?
      redirect_to root_path
    end
    @video = Video.find(params[:id])
    @video.update_attributes(video_params)
    if @video.save
      redirect_to videos_path
    end
  end

  def destroy
    if !admin_signed_in?
      redirect_to root_path
    end
    @video = Video.find(params[:id])
    if @video.destroy
      redirect_to videos_path
    end
  end

  private

  def video_params
    params.require(:video).permit(:url, :name, :key, :description, :section, :id)
  end

  def soundcloud_params
    params.require(:soundcloud).permit(:id, :button_name, :reference_number)
  end

end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/videos/edit.html.erb
<div class="container-fluid" style="padding: 0px; width: 100%; background-color: lightblue;">
	<div class="row home_section" style="margin-top: 50px;">
		<div class="col-md-4 col-push-md-4 col-xs-4">
		</div>
		<div class="col-md-5 col-push-md-7 col-xs-8">
			<%= form_for @video do |f| -%>
				<%= f.label :url %><br />
				<%= f.text_field :url, autofocus: true, :size => 80, class: "float_right" %><br />
				<%= f.label :name %><br />
				<%= f.text_field :name, :size => 80, class: "float_right" %><br />
				<%= f.label :key %><br />
				<%= f.text_field :key, :size => 80, class: "float_right" %><br />
				<%= f.label :description %><br />
				<%= f.text_field :description, :size => 80, class: "float_right" %><br />
				<%= f.label :section %><br />
				<%= f.select :section, ['lukes_compositions', 'weird_phishes', 'wikr', 'scoring_samples', 'featured_works'], class: "float_right" %><br />
				<%= f.submit "submit", class: "submit_button" %>
			<% end -%>
		</div>
		<div class="col-md-3 col-push-md-3 col-xs-3">
		</div>
	</div>
</div>

app/views/videos/index.html.erb
<div class="container-fluid lukes_compositions_block admin_index_blocks" style="padding: 0px; width: 100%; background-color: lightblue;">
	<div class="row home_section">
		<div class="col-md-8 col-push-md-7 col-xs-8">
		</div>
		<div class="col-md-3 col-push-md-7 col-xs-3">
			<button class="videos admin_weird_phishes">Weird Phishes</button>
			<button class="videos admin_wikr">Wikr</button>
			<button class="videos admin_featured_works">Featured Works</button>
			<button class="videos admin_soundcloud">Sound Cloud</button>
			<button class="videos admin_scoring_samples">Scoring Samples</button>  <hr>
			<% p @lukes_compositions.length %>
			<% if @lukes_compositions.length < 8 %>

				<%= form_for @video, :url => new_video_path, method: :get do |f| -%>
					<%= f.hidden_field :section, value: "lukes_compositions" %>
					<%= f.submit "Add New", class: "submit_button" %>
				<% end -%>
			<% else %>
				<h3>You have too many videos on this section, ether delete or edit one before you can add anouther.</h3>
			<% end %>
		</div>
	</div>
	<div class="row home_section">
		<div class="col-md-4 col-xs-4">
		</div>
		<div class="col-md-6 col-xs-6">
			<h1>Lukes Compositions</h1>
		</div>
	</div>
	<% @lukes_compositions.each do |video| %>
		<div class="row home_section">
			<div class="col-md-12 col-xs-12 center videos">
				<iframe width='100' height='100' src='https://www.youtube.com/embed/<%=video.key%>' style='margin: auto;' frameborder='0' allowfullscreen></iframe>
				<h4> <%= video.url  %> </h4>
				<h4> <%= video.name  %> </h4>
				<h4> <%= video.description  %> </h4>
				<h4> <%= video.section  %> </h4>
				<h4> <%= video.key  %> </h4>
				<%= button_to "Edit", "/videos/#{video.id}/edit", method: :get %>
				<%= button_to "Delete", "/videos/#{video.id}", method: :delete %> <hr>
			</div>
		</div>
	<% end %>
</div>

<div class="container-fluid weird_phishes_block admin_index_blocks hidden" style="padding: 0px; width: 100%; background-color: lightblue;">
	<div class="row home_section">
		<div class="col-md-8 col-push-md-7 col-xs-8">
		</div>
		<div class="col-md-3 col-push-md-7 col-xs-3">
			<button class="videos admin_lukes_compositions">Lukes Compositions </button>
			<button class="videos admin_wikr">Wikr</button>
			<button class="videos admin_featured_works">Featured Works</button>
			<button class="videos admin_soundcloud">Sound Cloud</button>
			<button class="videos admin_scoring_samples">Scoring Samples</button>  <hr>
			<% p @lukes_compositions.length %>
			<% if @weird_phishes.length < 8 %>

				<%= form_for @video, :url => new_video_path, method: :get do |f| -%>
					<%= f.hidden_field :section, value: "weird_phishes" %>
					<%= f.submit "Add New", class: "submit_button" %>
				<% end -%>
			<% else %>
				<h3>You have too many videos on this section, ether delete or edit one before you can add anouther.</h3>
			<% end %>
		</div>
	</div>
	<div class="row home_section">
		<div class="col-md-4 col-xs-4">
		</div>
		<div class="col-md-6 col-xs-6">
			<h1>Weird Phishes</h1>
		</div>
	</div>
	<% @weird_phishes.each do |video| %>
		<div class="row home_section">
			<div class="col-md-12 col-xs-12 center videos">
				<iframe width='100' height='100' src='https://www.youtube.com/embed/<%=video.key%>' style='margin: auto;' frameborder='0' allowfullscreen></iframe>
				<h4> <%= video.url  %> </h4>
				<h4> <%= video.name  %> </h4>
				<h4> <%= video.description  %> </h4>
				<h4> <%= video.section  %> </h4>
				<h4> <%= video.key  %> </h4>
				<%= button_to "Edit", "/videos/#{video.id}/edit", method: :get %>
				<%= button_to "Delete", "/videos/#{video.id}", method: :delete %> <hr>
			</div>
		</div>
	<% end %>
</div>

<div class="container-fluid wikr_block admin_index_blocks hidden" style="padding: 0px; width: 100%; background-color: lightblue;">
	<div class="row home_section">
		<div class="col-md-8 col-push-md-7 col-xs-8">
		</div>
		<div class="col-md-3 col-push-md-7 col-xs-3">
			<button class="videos admin_weird_phishes">Weird Phishes</button>
			<button class="videos admin_lukes_compositions">Lukes Compositions</button>
			<button class="videos admin_featured_works">Featured Works</button>
			<button class="videos admin_soundcloud">Sound Cloud</button>
			<button class="videos admin_scoring_samples">Scoring Samples</button> <hr>
			<% p @lukes_compositions.length %>
			<% if @wikr.length < 8 %>

				<%= form_for @video, :url => new_video_path, method: :get do |f| -%>
					<%= f.hidden_field :section, value: "wikr" %>
					<%= f.submit "Add New", class: "submit_button" %>
				<% end -%>
			<% else %>
				<h3>You have too many videos on this section, ether delete or edit one before you can add anouther.</h3>
			<% end %>
		</div>
	</div>
	<div class="row home_section">
		<div class="col-md-4 col-xs-4">
		</div>
		<div class="col-md-6 col-xs-6">
			<h1>Wickr</h1>
		</div>
	</div>
	<% @wikr.each do |video| %>
		<div class="row home_section">
			<div class="col-md-12 col-xs-12 center videos">
				<iframe width='100' height='100' src='https://www.youtube.com/embed/<%=video.key%>' style='margin: auto;' frameborder='0' allowfullscreen></iframe>
				<h4> <%= video.url  %> </h4>
				<h4> <%= video.name  %> </h4>
				<h4> <%= video.description  %> </h4>
				<h4> <%= video.section  %> </h4>
				<h4> <%= video.key  %> </h4>
				<%= button_to "Edit", "/videos/#{video.id}/edit", method: :get %>
				<%= button_to "Delete", "/videos/#{video.id}", method: :delete %> <hr>
			</div>
		</div>
	<% end %>
</div>

<div class="container-fluid scoring_samples_block admin_index_blocks hidden" style="padding: 0px; width: 100%; background-color: lightblue;">
	<div class="row home_section">
		<div class="col-md-8 col-push-md-7 col-xs-8">
		</div>
		<div class="col-md-3 col-push-md-7 col-xs-3">
			<button class="videos admin_weird_phishes">Weird Phishes</button>
			<button class="videos admin_wikr">Wikr</button>
			<button class="videos admin_lukes_compositions">Lukes Compositions</button>
			<button class="videos admin_soundcloud">Sound Cloud</button>
			<button class="videos admin_featured_works">Featured Works</button> <hr>
			<% p @scoring_samples.length %>
			<% if @scoring_samples.length < 2 %>

				<%= form_for @video, :url => new_video_path, method: :get do |f| -%>
					<%= f.hidden_field :section, value: "scoring_samples" %>
					<%= f.submit "Add New", class: "submit_button" %>
				<% end -%>
			<% else %>
				<h3>You have too many videos on this section, ether delete or edit one before you can add anouther.</h3>
			<% end %>
		</div>
	</div>
	<div class="row home_section">
		<div class="col-md-4 col-xs-4">
		</div>
		<div class="col-md-6 col-xs-6">
			<h1>Scoring Samples</h1>
		</div>
	</div>
	<% @scoring_samples.each do |video| %>
		<div class="row home_section">
			<div class="col-md-12 col-xs-12 center videos">
				<iframe width='100' height='100' src='https://www.youtube.com/embed/<%=video.key%>' style='margin: auto;' frameborder='0' allowfullscreen></iframe>
				<h4> <%= video.url  %> </h4>
				<h4> <%= video.name  %> </h4>
				<h4> <%= video.description  %> </h4>
				<h4> <%= video.section  %> </h4>
				<h4> <%= video.key  %> </h4>
				<%= button_to "Edit", "/videos/#{video.id}/edit", method: :get %>
				<%= button_to "Delete", "/videos/#{video.id}", method: :delete %> <hr>
			</div>
		</div>
	<% end %>
</div>

<div class="container-fluid featured_works_block admin_index_blocks hidden" style="padding: 0px; width: 100%; background-color: lightblue;">
	<div class="row home_section">
		<div class="col-md-8 col-push-md-7 col-xs-8">
		</div>
		<div class="col-md-3 col-push-md-7 col-xs-3">
			<button class="videos admin_weird_phishes">Weird Phishes</button>
			<button class="videos admin_wikr">Wikr</button>
			<button class="videos admin_scoring_samples">Scoring Samples</button>
			<button class="videos admin_soundcloud">Sound Cloud</button>
			<button class="videos admin_lukes_compositions">Lukes Compositions</button> <hr>
			<% p @featured_works.length %>
			<% if @featured_works.length < 2 %>

				<%= form_for @video, :url => new_video_path, method: :get do |f| -%>
					<%= f.hidden_field :section, value: "featured_works" %>
					<%= f.submit "Add New", class: "submit_button" %>
				<% end -%>
			<% else %>
				<h3>You have too many videos on this section, ether delete or edit one before you can add anouther.</h3>
			<% end %>
		</div>
	</div>
	<div class="row home_section">
		<div class="col-md-4 col-xs-4">
		</div>
		<div class="col-md-6 col-xs-6">
			<h1>Featured Works</h1>
		</div>
	</div>
	<% @featured_works.each do |video| %>
		<div class="row home_section">
			<div class="col-md-12 col-xs-12 center videos">
				<iframe width='100' height='100' src='https://www.youtube.com/embed/<%=video.key%>' style='margin: auto;' frameborder='0' allowfullscreen></iframe>
				<h4> <%= video.url  %> </h4>
				<h4> <%= video.name  %> </h4>
				<h4> <%= video.description  %> </h4>
				<h4> <%= video.section  %> </h4>
				<h4> <%= video.key  %> </h4>
				<%= button_to "Edit", "/videos/#{video.id}/edit", method: :get %>
				<%= button_to "Delete", "/videos/#{video.id}", method: :delete %> <hr>
			</div>
		</div>
	<% end %>
	<% @soundcloud_playlists.each do |playlist| %>


	<% end %>
</div>
<div class="container-fluid soundcloud_block admin_index_blocks hidden" style="padding: 0px; width: 100%; background-color: lightblue;">
	<div class="row home_section">
		<div class="col-md-8 col-push-md-7 col-xs-8">
		</div>
		<div class="col-md-3 col-push-md-7 col-xs-3">
			<button class="videos admin_weird_phishes">Weird Phishes</button>
			<button class="videos admin_wikr">Wikr</button>
			<button class="videos admin_lukes_compositions">Lukes Compositions</button>
			<button class="videos admin_soundcloud">Sound Cloud</button>
			<button class="videos admin_featured_works">Featured Works</button> <hr>
			<% p @soundcloud_playlists.length %>
			<% if @soundcloud_playlists.length < 6 %>

				<%= form_for @video, :url => new_soundcloud_path, method: :get do |f| -%>
					<%= f.hidden_field :section, value: "soundcloud_playlists" %>
					<%= f.submit "Add New", class: "submit_button" %>
				<% end -%>
			<% else %>
				<h3>You have too many videos on this section, ether delete or edit one before you can add anouther.</h3>
			<% end %>
		</div>
	</div>
	<div class="row home_section">
		<div class="col-md-4 col-xs-4">
		</div>
		<div class="col-md-6 col-xs-6">
			<h1>Sound Cloud</h1>
		</div>
	</div>
	<% @soundcloud_playlists.each do |playlist| %>
		<div class="row home_section">
			<div class="col-md-12 col-xs-12 center videos">
				<iframe width="100%" height="450" scrolling="no" frameborder="no" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/playlists/<%=playlist.reference_number%>&amp;color=ff5500&amp;auto_play=false&amp;hide_related=false&amp;show_comments=true&amp;show_user=true&amp;show_reposts=false"></iframe>
				<h4> <%= playlist.button_name  %> </h4>
				<h4> <%= playlist.reference_number  %> </h4>
				<%= button_to "Edit", "/soundcloud/#{playlist.id}/edit", method: :get %>
				<%= button_to "Delete", "/soundcloud/#{playlist.id}", method: :delete %> <hr>
			</div>
		</div>
	<% end %>
</div>

<script>
	$('.admin_weird_phishes').on('click', function() {
		$('.admin_index_blocks').addClass('hidden');
		$('.weird_phishes_block').removeClass('hidden');
	})
	$('.admin_wikr').on('click', function() {
		$('.admin_index_blocks').addClass('hidden');
		$('.wikr_block').removeClass('hidden');
	})
	$('.admin_lukes_compositions').on('click', function() {
		$('.admin_index_blocks').addClass('hidden');
		$('.lukes_compositions_block').removeClass('hidden');
	})
	$('.admin_scoring_samples').on('click', function() {
		$('.admin_index_blocks').addClass('hidden');
		$('.scoring_samples_block').removeClass('hidden');
	})
	$('.admin_featured_works').on('click', function() {
		$('.admin_index_blocks').addClass('hidden');
		$('.featured_works_block').removeClass('hidden');
	})
	$('.admin_soundcloud').on('click', function(){
		$('.admin_index_blocks').addClass('hidden');
		$('.soundcloud_block').removeClass('hidden');
	})
	var soundcloud_list = {genre_based_thematic_samples: '335414613', emotional: '329904726', action_intense: '329904489', horror_mysterious: '329904155', uplifting: '329904403', video_game_based: '336466351'};
	$(document).on('click', ".soundcloud_buttons", function() {
		current_playlist = $(this).attr('id');
		$('.loading_sound_cloud_mid').removeClass('hide');
		$('.soundcloud_widget_holder').html("<iframe id='soundcloud_iframe' width='500' height='450' scrolling='no' frameborder='no' src='https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/playlists/" + soundcloud_list[current_playlist] + "&amp;color=ff5500&amp;auto_play=false&amp;hide_related=false&amp;show_comments=true&amp;show_user=true&amp;show_reposts=false'></iframe>");
		$('.soundcloud_buttons').removeClass('clicked_soundcloud_buttons');
		$(this).addClass('clicked_soundcloud_buttons');
	})
</script>

app/views/videos/new.html.erb
<div class="container-fluid" style="padding: 0px; width: 100%; background-color: lightblue;">
	<div class="row home_section" style="margin-top: 50px;">
		<div class="col-md-4 col-push-md-4 col-xs-4">
		</div>
		<div class="col-md-5 col-push-md-7 col-xs-8">
			<%= form_for @video do |f| -%>
				<%= f.hidden_field :section, value: @section %>
				<%= f.label :url %><br />
				<%= f.text_field :url, autofocus: true, :size => 75, class: "float_right" %><br />
				<%= f.label :name %><br />
				<%= f.text_field :name, :size => 75, class: "float_right" %><br />
				<%= f.label :key %><br />
				<%= f.text_field :key, :size => 75, class: "float_right" %><br />
				<%= f.label :description %><br />
				<%= f.text_field :description, :size => 75, class: "float_right" %><br />
				<%= f.submit "submit", class: "submit_button" %>
			<% end -%>
		</div>
		<div class="col-md-3 col-push-md-3 col-xs-3">
		</div>
	</div>
</div>