config/routes.rb
Rails.application.routes.draw do

  
  resources :videos

  resources :soundcloud

  get 'content/reviews'
  
  get 'content/left_arrow'

  get 'content/right_arrow'

  get 'content/featured_works'

  get 'content/contact_us'

  post 'content/send_email'

  devise_for :admins, controllers: {
        sessions: 'admins/sessions'
      }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: "home#index"
end

app/controllers/content_controller.rb
class ContentController < ApplicationController
  def works
  end

  def featured_works
    @i = 0
    @lukes_compositions = Video.where(section: "lukes_compositions")
    @weird_phishes = Video.where(section: "weird_phishes")
    @wikr = Video.where(section: "wikr")
    @video = Video.new
  end

  def left_arrow
    @lukes_compositions = Video.where(section: "lukes_compositions")
    @weird_phishes = Video.where(section: "weird_phishes")
    @wikr = Video.where(section: "wikr")
    @video = Video.new
    respond_to do |format|
      @music_pages = ['lukes_compositions', 'weird_phishes', 'wikr']
      name = params[:video][:name]
      p name
      @i = @music_pages.index(name)
      @i = @i + 1 
      p @i
      if @i >2 then @i = 0 end 
      format.js
    end
  end

  def right_arrow
    @lukes_compositions = Video.where(section: "lukes_compositions")
    @weird_phishes = Video.where(section: "weird_phishes")
    @wikr = Video.where(section: "wikr")
    @video = Video.new
    respond_to do |format|
      @music_pages = ['lukes_compositions', 'weird_phishes', 'wikr']
      name = params[:video][:name]
      p name
      @i = @music_pages.index(name)
      @i = @i - 1 
      p @i
      if @i < 0 then @i = 2 end 
      format.js
    end
  end

  def reviews

  end

  def send_email
    p params
    cust_name = params[:first_name] + ' ' + params[:last_name]
    customer_email = params[:your_email]
    subject = cust_name + " " + params[:your_email]
    message = params[:message] + "!"
    p message
    
    RestClient.post "https://api:key-0b4b9928196d594ec7d29f57a4f6779b"\
    "@api.mailgun.net/v3/sandbox9e4f8f9b914e4318ac4b333b40daa36b.mailgun.org/messages",
    :from => "Mailgun Sandbox <postmaster@sandbox9e4f8f9b914e4318ac4b333b40daa36b.mailgun.org>",  #  need to change too a autherized domain
    :to => "audiowithdrawal@gmail.com", # change too send_to_email when done with testing and after you have set up autherized domain.  will ned to authorize recipients, ie send to emails.
    :subject => "#{subject}",
    :text => "#{message}"
    if status == 200
      redirect_to root_path, :flash => {:notice => "Email successfully sent"}
    else
      redirect_to root_path, :flash => {:alert => "Email was not sent correctly"}
    end
  end
end

app/helpers/content_helper.rb
module ContentHelper

end

app/views/content/_page_template.html.erb
<% type = instance_variable_get(("@" + name).intern) %>
<% i = @i %>
<div class="row home_section" style="height: 120px; overflow:hidden; text-align: center;">
	<div class="col-md-12 hidden-sm hidden-xs">
		<%= image_tag name + ".png", :size=> '1100x450' %>
	</div>
	<div class="hidden-xl hidden-lg hidden-md col-sm-12 hidden-xs">
		<%= image_tag name + ".png", :size=> '900x300' %>
	</div>
	<div class="hidden-xl hidden-lg hidden-md hidden-sm col-xs-12">
		<%= image_tag name + ".png", :size=> '600x250' %>
	</div>
	
</div>
<div class="row home_section hidden-sm hidden-xs" style="min-height: 100px;">
	<div class="col-md-1 hidden-sm hidden-xs">
	</div>
	<div class="col-md-3 col-xs-11" id="top_left" style="margin-left: 3%; margin-top: 2%;">
		<% if type[0] %>
			<%= works_imgs(name, type[0][:key]) %>
		<% end %>
	</div>
	
	<div class="col-md-3 col-xs-7 col-sm-7" id="top_middle" style="margin-left: 2%; margin-right: 1%;">
		<% if type[1] %>
			<%= works_imgs(name, type[1][:key]) %>
		<% end %>
	</div>
	
	<div class="col-md-3 col-xs-12" id="top_right" style="margin-top: 2%;">
		<% if type[2] %>
			<%= works_imgs(name, type[2][:key]) %>
		<% end %>
	</div>
</div>
<div class="row home_section" style="min-height: 250px; height: 100%;">
	<div class="col-md-1">
		<%= form_for @video, :url => content_left_arrow_path,:format => :js, method: :get, remote: :true, :rel => 'follow' do |f| -%>
			<%= f.hidden_field :name, value: name %>
			<%= button_tag( :class => "side_arrow left") do %>
				<svg width='60px' height='80px' viewBox='0 0 50 80' xml:space='preserve'><polyline fill='none' stroke='black' stroke-width='6' stroke-linecap='round' stroke-linejoin='round' points='45.63,75.8 0.375,38.087 45.63,0.375 '/><polyline fill='none' stroke='#FFFFFF' stroke-width='3' stroke-linecap='round' stroke-linejoin='round' points='45.63,75.8 0.375,38.087 45.63,0.375 '/></svg>
			<% end %>
		<% end %>
	</div>
	<div class="col-md-3  col-xs-7 col-sm-7 hidden-sm hidden-xs" id="mid_left" style="margin-top: 5%; min-height: 150px;">
		<% if type[3] %>
			<%= works_imgs(name, type[3][:key]) %>
		<% end %>
	</div>
	<div class="col-md-4 col-sm-12 col-xs-12 mid_mid you_tube_section" style="min-height: 150px;">
		<div class="page_page_mid" style=" min-height: 150px; height: 100%; width:100%; position: absolute;">
		</div>
	</div>
	<div class="col-lg-3 col-md-3 col-xs-7 hidden-sm hidden-xs" id="mid_right" style="margin-top: 5%; min-height: 150px;">
		<% if type[4] %>
			<%= works_imgs(name, type[4][:key]) %>
		<% end %>
	</div>
	<div class="col-md-1 ">
		<%= form_for @video, :url => content_right_arrow_path,:format => :js, method: :get, remote: :true, :rel => 'follow' do |f| -%>
			<%= f.hidden_field :name, value: name %>
			<%= button_tag( :class => "side_arrow right") do %>
				<svg xmlns='http://www.w3.org/2000/svg' xmlns:xlink='http://www.w3.org/1999/xlink' width='60px' height='80px' viewBox='0 0 50 80' xml:space='preserve'><polyline fill='none' stroke='black' stroke-width='6' stroke-linecap='round' stroke-linejoin='round' points='0.375,0.375 45.63,38.087 0.375,75.8 '/><polyline fill='none' stroke='#FFFFFF' stroke-width='3' stroke-linecap='round' stroke-linejoin='round' points='0.375,0.375 45.63,38.087 0.375,75.8 '/></svg>
			<% end %>
		<% end %>
	</div>
</div>
<div class="row home_section hidden-sm hidden-xs" style="margin-top: 1%;">
	<div class="col-md-1 hidden-sm hidden-xs">
	</div>
	<div class="col-md-3  col-xs-7 col-sm-7" id="bottom_left" style="margin-left: 3%;">
		<% if type[5] %>
			<%= works_imgs(name, type[5][:key]) %>
		<% end %>
	</div>
	<div class="col-md-3  col-xs-7 col-sm-7" id="bottom_mid" style="margin-left: 2%; margin-right: 1%;">
		<% if type[6] %>
			<%= works_imgs(name, type[6][:key]) %>
		<% end %>
	</div>
	<div class="col-md-3  col-xs-7 col-sm-7" id="bottom_right">
		<% if type[7] %>
			<%= works_imgs(name, type[7][:key]) %>
		<% end %>
	</div>
</div>


<br>
<div class="row home_section hidden-md hidden-lg hidden-xl" style="min-height: 120px; overflow:hidden; margin-top: 100px;">
	<div class="col-sm-1 col-xs-1">
		
	</div>
	<div class="col-md-3 col-xs-5" id="top_left" style="width: 40%;">
		<% if type[0] %>
			<%= works_imgs(name, type[0][:key]) %>
		<% end %>
	</div>
	<div class="col-md-4 col-xs-5 col-sm-5" id="top_middle">
		<% if type[1] %>
			<%= works_imgs(name, type[1][:key]) %>
		<% end %>
	</div>
</div> <br>
<div class="row home_section hidden-md hidden-lg hidden-xl" style="min-height: 120px; overflow:hidden;">
	<div class="col-sm-1 col-xs-1">
		
	</div>
	<div class="col-md-3 col-xs-5" id="top_right" style="width: 40%;">
		<% if type[2] %>
			<%= works_imgs(name, type[2][:key]) %>
		<% end %>
	</div>
	<div class="col-md-2  col-xs-5 col-sm-5" id="mid_left"">
		<% if type[3] %>
			<%= works_imgs(name, type[3][:key]) %>
		<% end %>
	</div>
</div> <br>
<div class="row home_section hidden-md hidden-lg hidden-xl" style="min-height: 120px; overflow:hidden;">
	<div class="col-sm-1 col-xs-1">
		
	</div>
	<div class="col-lg-3 col-md-3  col-xs-5 col-sm-5" id="mid_right"  style="width: 40%; margin-left: 0px;">
		<% if type[4] %>
			<%= works_imgs(name, type[4][:key]) %>
		<% end %>
	</div>
	<div class="col-md-3  col-xs-5 col-sm-5" id="bottom_left">
		<% if type[5] %>
			<%= works_imgs(name, type[5][:key]) %>
		<% end %>
	</div>
</div> <br>
<div class="row home_section hidden-md hidden-lg hidden-xl" style="min-height: 120px; overflow:hidden;">
	<div class="col-sm-1 col-xs-1">
		
	</div>
	<div class="col-md-4  col-xs-5 col-sm-5" id="bottom_mid" style="width: 40%;">
		<% if type[6] %>
			<%= works_imgs(name, type[6][:key]) %>
		<% end %>
	</div>
	<div class="  col-xs-5 col-sm-5" id="bottom_right">
		<% if type[7] %>
			<%= works_imgs(name, type[7][:key]) %>
		<% end %>
	</div>
</div>

app/views/content/contact_us.html.erb
<%
meta title: "Contact Us",
     description: "Contact Audio Withdrawal",
     robots: "index",
     keywords: %w(Luke Wickman, Audio Withdrawal, composer, compositions, music, scoring, sound engineers, Weird Phishes, Wikr, aw)
%>
<div class="container-fluid" style="background-color: white; height: 500px;">
	<div class="row basic_border green">
		<div class="col-md-12 col-sm-12 center white_text">
			<h5>Any questions please reach out</h5>
			<h5>audiowithdrawal@gmail.com</h5>
		</div>
	</div>
	<div class="row shading email_container" style="margin-top: 10px; margin-left: 50px;">

		<%= form_tag('/content/send_email') do |f| %>
			<%= hidden_field_tag :send_to_email, nil, class:"send_to_email" %><br />
			<%= text_area_tag :first_name, nil, size: "20x1", class: "customer_name", placeholder: "First Name" %>
			<%= text_area_tag :last_name, nil, size: "20x1", class: "customer_name", placeholder: "Last Name" %><br>
			<%= text_area_tag :your_email, nil, size: "45x1", class: "customer_email", placeholder: "Your Email" %><br>
			
			<%= text_area_tag :message, nil, size: "100x8", class: "customer_input", placeholder: "Enter message" %><hr>
			<%= submit_tag "Send", class: "submit_email" %>
		<% end %>
	</div>
</div>

app/views/content/featured_works.html.erb
<%
meta title: "Featured works",
     description: "Audio Compositions",
     robots: "index",
     keywords: %w(Luke Wickman, Audio Withdrawal, composer, compositions, music, scoring, sound engineers, Weird Phishes, Wikr, aw)
%>
<div class="container-fluid lukes_compositions_page page fullscreen_list" id="container" style="padding-left: 30px; width: 97%; min-height: 700px; height: 100%;">
	<% music_pages = ['lukes_compositions', 'weird_phishes', 'wikr']  %>
	<% i = @i %>
	<%= render 'page_template', name: music_pages[i] %> 
</div>

app/views/content/left_arrow.js.erb
$('#container').html("<%= escape_javascript(render partial: 'content/page_template', locals: {name: @music_pages[@i]})  %>");
$('#container').removeClass();
$('#container').addClass("container-fluid page <%= @music_pages[@i] %>_page");

app/views/content/reviews.html.erb
<h1>reviews</h1>

app/views/content/right_arrow.js.erb
$('#container').html("<%= escape_javascript(render partial: 'content/page_template', locals: {name: @music_pages[@i]})  %>");
$('#container').removeClass();
$('#container').addClass("container-fluid page <%= @music_pages[@i] %>_page");