config/routes.rb
Rails.application.routes.draw do

  
  resources :videos

  resources :soundcloud

  get 'content/reviews'
  
  get 'content/left_arrow'

  get 'content/right_arrow'

  get 'content/featured_works'

  get 'content/contact_us'

  post 'content/send_email'

  devise_for :admins, controllers: {
        sessions: 'admins/sessions'
      }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: "home#index"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <%= csrf_meta_tags %>
    <%= favicon_link_tag 'favi.ico' %>
    <%= metamagic %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <% if Rails.env.production? %>
        <script type="text/javascript">
            (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
            (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
            m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
            })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');
            ga('create', 'UA-102639931-1', 'auto');
        </script>
    <% end %>
  </head>

  <body>


	<div id="wrapper">
        <div class="overlay"></div>
        
        <!-- Sidebar -->
        <nav class="navbar navbar-fixed-top" id="sidebar-wrapper" role="navigation">
            <ul class="nav sidebar-nav">
                <ul class='company_name' style='height:80px'>
                    <%= link_to image_tag('aw_logo.png', :class => "logo_image float_right"), root_path %>
                </ul>
                <% if current_page?(root_path) %> 
                    <li>
                        <a class="scroll_button home_button">Home<i class='sub_icon glyphicon glyphicon-home'></i></a>
                    </li>
                    <li>
                        <a class="scroll_button intro_button">Intro<i class='sub_icon glyphicon glyphicon-user'></i></a>
                    </li>
                    <li>
                        <a class="scroll_button featured_works_button">Samples<i class='sub_icon glyphicon glyphicon-star-empty'></i></a>
                    </li>
                    <li>
                        <%= link_to raw(" Featured <i class=' glyphicon glyphicon-cd' style='float: right; margin-top: 11px; margin-right: 25px;'></i>"), content_featured_works_path, :rel => 'follow' %>
                    </li>
                    <li>
                        <a class="scroll_button contact_us_button">Contact Us<i class='sub_icon glyphicon glyphicon-phone-alt'></i></a>
                    </li>
                    <ul style="padding-left: 0px; padding-top: 20px;">
                        <%= link_to image_tag("Twit.png", :size=> '70x70'), "https://twitter.com/AudioWithdrawal" %>
                        <%= link_to image_tag("twitch.png", :size=> '70x70'), "https://www.twitch.tv/audiowithdrawal" %>
                        <%= link_to image_tag("utub.png", :size=> '70x70'), "https://www.youtube.com/channel/UCKH1iz7ic0OVXmktxeUL3AA" %>
                       
                    </ul>
                    <ul style="padding-left: 0px;">
                        <%= link_to image_tag("fbook.png", :size=> '70x70'), "https://www.facebook.com/AudioWithdrawal/" %>
                        <%= link_to image_tag("bc.png", :size=> '70x70'), "https://audiowithdrawal.bandcamp.com/" %>
                        <%= link_to image_tag("cloud.png", :size=> '70x70'), "https://soundcloud.com/audiowithdrawal" %>
                        
                    </ul>
                <% else %>
                    <li>
                        <%= link_to raw(" Home <i class='glyphicon glyphicon-home' style='float: right; margin-top: 11px; margin-right: 15px;'></i>"), root_path, :rel => 'follow' %>
                    </li>
                    <li>
                        <%= link_to raw(" Featured <i class=' glyphicon glyphicon-cd' style='float: right; margin-top: 11px; margin-right: 15px;'></i>"), content_featured_works_path, :rel => 'follow' %>
                    </li>
                    <li>
                        <%= link_to raw(" Contact Us <i class='glyphicon glyphicon-phone-alt' style='float: right; margin-top: 11px; margin-right: 15px;'></i>"), content_contact_us_path, :rel => 'follow' %>
                    </li>
                <% end %>
            </ul>
        </nav>
        <div id="page-content-wrapper">
          <button type="button" class="hamburger is-closed animated fadeInLeft" data-toggle="offcanvas">
            <span class="hamb-top"></span>
            <span class="hamb-middle"></span>
            <span class="hamb-bottom"></span>
          </button>
          
        </div>

        <%= yield :javascript %>


        <% if flash[:notice] || flash[:alert] %>
            <p class="notice" style="background-color: white, font-size: 150%;, text-align: center;" ><%= notice %></p>
            <p class="alert" style="background-color: white, font-size: 150%;, text-align: center;" ><%= alert %></p>
        <% end %>


        <%= yield %>


        <footer class="page-footer blue center-on-small-only" style="width: 97.7%">
            <div class="container-fluid" style="padding: 0px; width: 100%;">
            <div class="row">
                <div class="col-md-1 col-xs-1">
                </div>
                <div class="col-md-5 col-xs-5">
                    <p>Any Questions please reach out</p>
                </div>
                <div class="col-md-2 col-xs-2">
                    <h5 class="title">Links</h5>
                    <ul>
                        <li><%= link_to "Works ", content_featured_works_path, method: :get, class: 'white', :rel => 'follow' %></li>
                        <li><%= link_to "Contact Us ", content_contact_us_path, method: :get, class: 'white', :rel => 'follow' %></li>
                        <% if !current_admin %>
                            <li><%= link_to "Admin", new_admin_session_path, method: :get, class: 'white' %></li>
                        <% else %>
                            <li><%= link_to "Admin", videos_path, method: :get, class: 'white' %></li>
                            <li><%= link_to "Log Out", destroy_admin_session_path, method: :delete, class: 'white' %></li>
                        <% end %>
                    </ul>
                </div>
            </div>
            <div class="row">
                <div class="col-md-1">
                </div>
                <div class="col-md-11">
                    © 2017 Copyright AudioWithdrawal

                </div>
            </div>
        </footer>
    </div>
  </body>
</html>